ktor:
  environment: "PROD" # DEV, PROD
  application:
    modules:
        - com.mehrbod.ApplicationKt.module
  deployment:
    port: 8080
database:
  h2:
    host: "localhost"
    driver: "h2"
    protocol: "mem"
    database: "test"
    user: ""
    password: ""
  postgres:
    url: "postgresql://postgres:5432/employee"
    host: "postgres"
    driver: "postgres"
    protocol: "file"
    database: "employee"
    user: "username"
    password: "password"
redis:
  url: "redis://redis:6379"
kafka:
  schema:
    registry:
      url: "http://schema-registry:8081"
  common:
    bootstrap:
      servers: "broker:9092"
  admin:
  consumer:
    group.id: "notification-group"
  producer:
    client.id: "my-client-id"
